GET http://localhost:3000/about

###
GET http://localhost:3000/ping

//users
###
GET http://localhost:3000/users/

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Jose",
    "email": "jose@gmail.com",
    "password": "securepassword123"
}

###
GET http://localhost:3000/users/22

###
PUT http://localhost:3000/users/12
Content-Type: application/json

{
    "name": "Arelys",
    "email": "arelys@gmail.com"
}

###
DELETE http://localhost:3000/users/4

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "AdminTest",
    "email": "admintest@gmail.com",
    "password": "admintest123"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "name": "Antonio",
    "password": "antonio123"
}

//categories

###
GET http://localhost:3000/categories

###
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Vehiculos y Pistas",
    "description": "Juguetes suaves y abrazables que transmiten ternura y compañía. Incluyen ositos, muñecas y personajes de películas o animales de peluche."
}

###
PUT http://localhost:3000/categories/2
Content-Type: application/json

{
    "description": "Carritos, trenes, aviones y pistas de carreras para juego dinámico."
}

###
DELETE http://localhost:3000/categories/6


//tags

###
GET http://localhost:3000/tags

###
POST http://localhost:3000/tags
Content-Type: application/json


{
    "name": "Infantil"
}
    
###
PUT http://localhost:3000/tags/2
Content-Type: application/json

{
    "name": "Clásico"
}

###
DELETE http://localhost:3000/tags/2

//products

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Playmobil Castillo Medieval",
    "description": "Set de juego con caballeros, armas y murallas para recrear batallas.",
    "categoryId": 2,
    "ageRange": 7,
    "price": 74.99,
    "stock": 20,
    "sku": "PLAYMOBIL-001",
    "tags": [2, 3, 6] 
}

###
GET http://localhost:3000/products/

###
PUT http://localhost:3000/products/1
Content-Type: application/json

{
    "name": "LEGO Star Wars X-Wing",
    "slug": "lego-star-wars-xwing",
    "description": "Set de construcción con 700 piezas inspirado en la saga Star Wars.",
    "categoryId": 1,
    "ageRange": 8,
    "price": 89.99,
    "stock": 15,
    "sku": "LEGO-001",
    "tags": [1, 4, 6] 
}

###
DELETE http://localhost:3000/products/2

###
POST http://localhost:3000/orders
Content-Type: application/json

{
    "Items":[
        {"productId": 1, "quantity": 5},
        {"productId": 8, "quantity": 1}
    ],
    "paymentMethod": "CreditCard",
    "paymentDetails":{
        "card-number": "4111111111111111",
        "cvv": "123",
        "expiration-month": "01",
        "expiration-year": "2029",
        "full-name": "APROVED",
        "currency": "USD",
        "description": "cool stuff"
    }
}


###
GET http://localhost:3000/orders/

###

GET http://localhost:3000/orders?page=1