GET http://localhost:3000/about

###
GET http://localhost:3000/ping

###
GET http://localhost:3000/users/

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Jose",
    "email": "jose@gmail.com",
    "password": "securepassword123"
}

###
PUT http://localhost:3000/users/8
Content-Type: application/json

{
    "email": "jhon2@gmail.com"
}

###
DELETE http://localhost:3000/users/1

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "Antonio",
    "email": "antonito12@gmail.com",
    "password": "antonio123"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "name": "Antonio",
    "password": "antonio123"
}