GET http://localhost:3000/about

###
GET http://localhost:3000/ping

###
GET http://localhost:3000/users/

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Jose",
    "email": "jose@gmail.com",
    "password": "securepassword123"
}

###
PUT http://localhost:3000/users/12
Content-Type: application/json

{
    "name": "Arelys",
    "email": "arelys@gmail.com"
}

###
DELETE http://localhost:3000/users/4

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@gmail.com",
    "password": "admin123"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "name": "Admin",
    "password": "admin123"
}